// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: executions.sql

package sqlc

import (
	"context"
	"time"
)

const completeExecution = `-- name: CompleteExecution :exec
UPDATE executions
SET status = ?1,
    finished_at = ?2,
    report = ?3
WHERE id = ?4
`

type CompleteExecutionParams struct {
	Status     string
	FinishedAt *time.Time
	Report     *string
	ID         int64
}

func (q *Queries) CompleteExecution(ctx context.Context, arg CompleteExecutionParams) error {
	_, err := q.db.ExecContext(ctx, completeExecution,
		arg.Status,
		arg.FinishedAt,
		arg.Report,
		arg.ID,
	)
	return err
}

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (workflow_id, trigger_type, status, queued_at, started_at, finished_at, report)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7
)
RETURNING id, workflow_id, trigger_type, status, queued_at, started_at, finished_at, report
`

type CreateExecutionParams struct {
	WorkflowID  string
	TriggerType string
	Status      string
	QueuedAt    time.Time
	StartedAt   *time.Time
	FinishedAt  *time.Time
	Report      *string
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRowContext(ctx, createExecution,
		arg.WorkflowID,
		arg.TriggerType,
		arg.Status,
		arg.QueuedAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Report,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TriggerType,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Report,
	)
	return i, err
}

const deleteExecutionOverflowByWorkflow = `-- name: DeleteExecutionOverflowByWorkflow :exec
DELETE FROM executions
WHERE id IN (
  SELECT stale.id
  FROM executions AS stale
  WHERE stale.workflow_id = ?1
    AND stale.status NOT IN (?2, ?3)
  ORDER BY COALESCE(stale.finished_at, stale.started_at, stale.queued_at) DESC, stale.id DESC
  LIMIT -1 OFFSET ?4
)
`

type DeleteExecutionOverflowByWorkflowParams struct {
	WorkflowID    string
	QueuedStatus  string
	RunningStatus string
	KeepLimit     int64
}

func (q *Queries) DeleteExecutionOverflowByWorkflow(ctx context.Context, arg DeleteExecutionOverflowByWorkflowParams) error {
	_, err := q.db.ExecContext(ctx, deleteExecutionOverflowByWorkflow,
		arg.WorkflowID,
		arg.QueuedStatus,
		arg.RunningStatus,
		arg.KeepLimit,
	)
	return err
}

const deleteExecutionsOlderThan = `-- name: DeleteExecutionsOlderThan :exec
DELETE FROM executions
WHERE status NOT IN (?1, ?2)
  AND finished_at IS NOT NULL
  AND finished_at < ?3
`

type DeleteExecutionsOlderThanParams struct {
	QueuedStatus  string
	RunningStatus string
	Cutoff        *time.Time
}

func (q *Queries) DeleteExecutionsOlderThan(ctx context.Context, arg DeleteExecutionsOlderThanParams) error {
	_, err := q.db.ExecContext(ctx, deleteExecutionsOlderThan, arg.QueuedStatus, arg.RunningStatus, arg.Cutoff)
	return err
}

const getExecution = `-- name: GetExecution :one
SELECT id, workflow_id, trigger_type, status, queued_at, started_at, finished_at, report
FROM executions
WHERE id = ?1
`

func (q *Queries) GetExecution(ctx context.Context, id int64) (Execution, error) {
	row := q.db.QueryRowContext(ctx, getExecution, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TriggerType,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Report,
	)
	return i, err
}

const latestExecutionByWorkflow = `-- name: LatestExecutionByWorkflow :one
SELECT id, workflow_id, trigger_type, status, queued_at, started_at, finished_at, report
FROM executions
WHERE workflow_id = ?1
ORDER BY COALESCE(finished_at, started_at, queued_at) DESC, id DESC
LIMIT 1
`

func (q *Queries) LatestExecutionByWorkflow(ctx context.Context, workflowID string) (Execution, error) {
	row := q.db.QueryRowContext(ctx, latestExecutionByWorkflow, workflowID)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TriggerType,
		&i.Status,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Report,
	)
	return i, err
}

const listQueuedExecutionVersionsByWorkflow = `-- name: ListQueuedExecutionVersionsByWorkflow :many
SELECT q.execution_id, w.name, w.version
FROM queue q
JOIN workflows w ON w.id = q.workflow_id
WHERE q.workflow_id = ?1
`

type ListQueuedExecutionVersionsByWorkflowRow struct {
	ExecutionID int64
	Name        string
	Version     string
}

func (q *Queries) ListQueuedExecutionVersionsByWorkflow(ctx context.Context, workflowID string) ([]ListQueuedExecutionVersionsByWorkflowRow, error) {
	rows, err := q.db.QueryContext(ctx, listQueuedExecutionVersionsByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQueuedExecutionVersionsByWorkflowRow
	for rows.Next() {
		var i ListQueuedExecutionVersionsByWorkflowRow
		if err := rows.Scan(&i.ExecutionID, &i.Name, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleRunningExecutions = `-- name: ListStaleRunningExecutions :many
SELECT e.id, e.workflow_id, w.name, w.version
FROM executions e
JOIN workflows w ON w.id = e.workflow_id
WHERE e.status = ?1
`

type ListStaleRunningExecutionsRow struct {
	ID         int64
	WorkflowID string
	Name       string
	Version    string
}

func (q *Queries) ListStaleRunningExecutions(ctx context.Context, status string) ([]ListStaleRunningExecutionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStaleRunningExecutions, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleRunningExecutionsRow
	for rows.Next() {
		var i ListStaleRunningExecutionsRow
		if err := rows.Scan(&i.ID, &i.WorkflowID, &i.Name, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExecutionRunning = `-- name: MarkExecutionRunning :exec
UPDATE executions
SET status = ?1,
    started_at = ?2,
    finished_at = NULL
WHERE id = ?3
`

type MarkExecutionRunningParams struct {
	Status    string
	StartedAt *time.Time
	ID        int64
}

func (q *Queries) MarkExecutionRunning(ctx context.Context, arg MarkExecutionRunningParams) error {
	_, err := q.db.ExecContext(ctx, markExecutionRunning, arg.Status, arg.StartedAt, arg.ID)
	return err
}
