// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"
)

type Execution struct {
	ID          int64
	WorkflowID  string
	TriggerType string
	Status      string
	QueuedAt    time.Time
	StartedAt   *time.Time
	FinishedAt  *time.Time
	Report      *string
}

type Queue struct {
	ID             int64
	ExecutionID    int64
	WorkflowID     string
	TriggerType    string
	TriggerContext string
	QueuedAt       time.Time
}

type Trigger struct {
	ID         int64
	WorkflowID string
	Type       string
	Config     string
	NextRunAt  *time.Time
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Workflow struct {
	ID        string
	Name      string
	Version   string
	Path      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
