// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queue.sql

package sqlc

import (
	"context"
	"time"
)

const countQueueByWorkflow = `-- name: CountQueueByWorkflow :one
SELECT COUNT(*)
FROM queue
WHERE workflow_id = ?1
`

func (q *Queries) CountQueueByWorkflow(ctx context.Context, workflowID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQueueByWorkflow, workflowID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQueueItem = `-- name: CreateQueueItem :one
INSERT INTO queue (execution_id, workflow_id, trigger_type, trigger_context, queued_at)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5
)
RETURNING id, execution_id, workflow_id, trigger_type, trigger_context, queued_at
`

type CreateQueueItemParams struct {
	ExecutionID    int64
	WorkflowID     string
	TriggerType    string
	TriggerContext string
	QueuedAt       time.Time
}

func (q *Queries) CreateQueueItem(ctx context.Context, arg CreateQueueItemParams) (Queue, error) {
	row := q.db.QueryRowContext(ctx, createQueueItem,
		arg.ExecutionID,
		arg.WorkflowID,
		arg.TriggerType,
		arg.TriggerContext,
		arg.QueuedAt,
	)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.WorkflowID,
		&i.TriggerType,
		&i.TriggerContext,
		&i.QueuedAt,
	)
	return i, err
}

const deleteQueueByWorkflow = `-- name: DeleteQueueByWorkflow :exec
DELETE FROM queue
WHERE workflow_id = ?1
`

func (q *Queries) DeleteQueueByWorkflow(ctx context.Context, workflowID string) error {
	_, err := q.db.ExecContext(ctx, deleteQueueByWorkflow, workflowID)
	return err
}

const deleteQueueItem = `-- name: DeleteQueueItem :exec
DELETE FROM queue
WHERE id = ?1
`

func (q *Queries) DeleteQueueItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteQueueItem, id)
	return err
}

const getNextQueueItemByWorkflow = `-- name: GetNextQueueItemByWorkflow :one
SELECT id, execution_id, workflow_id, trigger_type, trigger_context, queued_at
FROM queue
WHERE workflow_id = ?1
ORDER BY queued_at, id
LIMIT 1
`

func (q *Queries) GetNextQueueItemByWorkflow(ctx context.Context, workflowID string) (Queue, error) {
	row := q.db.QueryRowContext(ctx, getNextQueueItemByWorkflow, workflowID)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.WorkflowID,
		&i.TriggerType,
		&i.TriggerContext,
		&i.QueuedAt,
	)
	return i, err
}
