// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: triggers.sql

package sqlc

import (
	"context"
	"time"
)

const createTrigger = `-- name: CreateTrigger :one
INSERT INTO triggers (workflow_id, type, config, next_run_at, status, created_at, updated_at)
VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7
)
RETURNING id, workflow_id, type, config, next_run_at, status, created_at, updated_at
`

type CreateTriggerParams struct {
	WorkflowID string
	Type       string
	Config     string
	NextRunAt  *time.Time
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) CreateTrigger(ctx context.Context, arg CreateTriggerParams) (Trigger, error) {
	row := q.db.QueryRowContext(ctx, createTrigger,
		arg.WorkflowID,
		arg.Type,
		arg.Config,
		arg.NextRunAt,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Trigger
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Type,
		&i.Config,
		&i.NextRunAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTriggersByWorkflow = `-- name: DeleteTriggersByWorkflow :exec
DELETE FROM triggers
WHERE workflow_id = ?1
`

func (q *Queries) DeleteTriggersByWorkflow(ctx context.Context, workflowID string) error {
	_, err := q.db.ExecContext(ctx, deleteTriggersByWorkflow, workflowID)
	return err
}

const listTriggersByWorkflow = `-- name: ListTriggersByWorkflow :many
SELECT id, workflow_id, type, config, next_run_at, status, created_at, updated_at
FROM triggers
WHERE workflow_id = ?1
ORDER BY id
`

func (q *Queries) ListTriggersByWorkflow(ctx context.Context, workflowID string) ([]Trigger, error) {
	rows, err := q.db.QueryContext(ctx, listTriggersByWorkflow, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trigger
	for rows.Next() {
		var i Trigger
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Type,
			&i.Config,
			&i.NextRunAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTriggerRuntime = `-- name: SetTriggerRuntime :exec
UPDATE triggers
SET status = ?1,
    next_run_at = ?2,
    updated_at = ?3
WHERE id = ?4
`

type SetTriggerRuntimeParams struct {
	Status    string
	NextRunAt *time.Time
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) SetTriggerRuntime(ctx context.Context, arg SetTriggerRuntimeParams) error {
	_, err := q.db.ExecContext(ctx, setTriggerRuntime,
		arg.Status,
		arg.NextRunAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
