// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: workflows.sql

package sqlc

import (
	"context"
	"time"
)

const countActiveWorkflows = `-- name: CountActiveWorkflows :one
SELECT COUNT(*)
FROM workflows
WHERE status = ?1
`

func (q *Queries) CountActiveWorkflows(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveWorkflows, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows
WHERE id = ?1
`

func (q *Queries) DeleteWorkflow(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkflow, id)
	return err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, name, version, path, status, created_at, updated_at
FROM workflows
WHERE id = ?1
`

func (q *Queries) GetWorkflow(ctx context.Context, id string) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Path,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveWorkflows = `-- name: ListActiveWorkflows :many
SELECT id, name, version, path, status, created_at, updated_at
FROM workflows
WHERE status = ?1
ORDER BY name, version, id
`

func (q *Queries) ListActiveWorkflows(ctx context.Context, status string) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWorkflows, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Path,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, name, version, path, status, created_at, updated_at
FROM workflows
ORDER BY name, version, id
`

func (q *Queries) ListWorkflows(ctx context.Context) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Path,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkflowStatus = `-- name: SetWorkflowStatus :exec
UPDATE workflows
SET status = ?1, updated_at = ?2
WHERE id = ?3
`

type SetWorkflowStatusParams struct {
	Status    string
	UpdatedAt time.Time
	ID        string
}

func (q *Queries) SetWorkflowStatus(ctx context.Context, arg SetWorkflowStatusParams) error {
	_, err := q.db.ExecContext(ctx, setWorkflowStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}

const upsertWorkflow = `-- name: UpsertWorkflow :exec
INSERT INTO workflows (id, name, version, path, status, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  version = excluded.version,
  path = excluded.path,
  status = excluded.status,
  updated_at = excluded.updated_at
`

type UpsertWorkflowParams struct {
	ID        string
	Name      string
	Version   string
	Path      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) UpsertWorkflow(ctx context.Context, arg UpsertWorkflowParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkflow,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Path,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
